apiVersion: v1  # Menggunakan API versi 1 untuk resource Namespace
kind: Namespace  # Menentukan bahwa ini adalah resource Namespace

metadata:
  name: monitoring  # Namespace terpisah untuk Prometheus & Grafana agar tidak bercampur dengan aplikasi Karsa Jobs
